 services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile_Node
    ports:
      - "2001:8080"
      
  web:
    build: 
      context: .
      dockerfile: Dockerfile_Web
    ports:
      - "2000:8080"